// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Skolio.Organization.Infrastructure.Persistence;

#nullable disable

namespace Skolio.Organization.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrganizationDbContext))]
    [Migration("20260311180000_Phase3SchoolContextMatrix")]
    partial class Phase3SchoolContextMatrix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
