// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Skolio.Organization.Infrastructure.Persistence;

#nullable disable

namespace Skolio.Organization.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrganizationDbContext))]
    [Migration("20260311195545_PhaseValidationOrganizationSync")]
    partial class PhaseValidationOrganizationSync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.ClassRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("GradeLevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_level_id");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.HasKey("Id");

                    b.ToTable("class_rooms", (string)null);
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.Founder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FounderCategory")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("founder_category");

                    b.Property<string>("FounderDataBox")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("founder_data_box");

                    b.Property<string>("FounderEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("founder_email");

                    b.Property<string>("FounderIco")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("founder_ico");

                    b.Property<string>("FounderLegalForm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("founder_legal_form");

                    b.Property<string>("FounderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("founder_name");

                    b.Property<string>("FounderType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("founder_type");

                    b.HasKey("Id");

                    b.HasIndex("FounderCategory");

                    b.HasIndex("FounderType");

                    b.ToTable("founders", (string)null);
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.GradeLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.HasKey("Id");

                    b.ToTable("grade_levels", (string)null);
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EducationLocationsSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("education_locations_summary");

                    b.Property<DateOnly?>("EducationStartDate")
                        .HasColumnType("date")
                        .HasColumnName("education_start_date");

                    b.Property<Guid?>("FounderId")
                        .HasColumnType("uuid")
                        .HasColumnName("founder_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int?>("MaxStudentCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("max_student_capacity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PlatformStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Active")
                        .HasColumnName("platform_status");

                    b.Property<DateOnly?>("RegistryEntryDate")
                        .HasColumnType("date")
                        .HasColumnName("registry_entry_date");

                    b.Property<Guid?>("SchoolAdministratorUserProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_administrator_user_profile_id");

                    b.Property<string>("SchoolEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("school_email");

                    b.Property<string>("SchoolIzo")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("school_izo");

                    b.Property<string>("SchoolKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("General")
                        .HasColumnName("school_kind");

                    b.Property<Guid?>("SchoolOperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_operator_id");

                    b.Property<string>("SchoolPhone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("school_phone");

                    b.Property<string>("SchoolType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("school_type");

                    b.Property<string>("SchoolWebsite")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("school_website");

                    b.Property<string>("TeachingLanguage")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("teaching_language");

                    b.HasKey("Id");

                    b.HasIndex("FounderId");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.HasIndex("SchoolIzo");

                    b.HasIndex("SchoolOperatorId");

                    b.HasIndex("SchoolType");

                    b.ToTable("schools", (string)null);
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.SchoolContextScopeAllowedAcademicsSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MatrixId")
                        .HasColumnType("uuid")
                        .HasColumnName("matrix_id");

                    b.Property<string>("SectionCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("section_code");

                    b.Property<string>("TranslationKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("translation_key");

                    b.HasKey("Id");

                    b.HasIndex("MatrixId", "SectionCode")
                        .IsUnique();

                    b.ToTable("school_context_scope_allowed_academics_sections", (string)null);
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.SchoolContextScopeAllowedCreateUserFlow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FlowCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("flow_code");

                    b.Property<Guid>("MatrixId")
                        .HasColumnType("uuid")
                        .HasColumnName("matrix_id");

                    b.Property<string>("TranslationKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("translation_key");

                    b.HasKey("Id");

                    b.HasIndex("MatrixId", "FlowCode")
                        .IsUnique();

                    b.ToTable("school_context_scope_allowed_create_user_flows", (string)null);
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.SchoolContextScopeAllowedOrganizationSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MatrixId")
                        .HasColumnType("uuid")
                        .HasColumnName("matrix_id");

                    b.Property<string>("SectionCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("section_code");

                    b.Property<string>("TranslationKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("translation_key");

                    b.HasKey("Id");

                    b.HasIndex("MatrixId", "SectionCode")
                        .IsUnique();

                    b.ToTable("school_context_scope_allowed_organization_sections", (string)null);
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.SchoolContextScopeAllowedProfileSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MatrixId")
                        .HasColumnType("uuid")
                        .HasColumnName("matrix_id");

                    b.Property<string>("SectionCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("section_code");

                    b.Property<string>("TranslationKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("translation_key");

                    b.HasKey("Id");

                    b.HasIndex("MatrixId", "SectionCode")
                        .IsUnique();

                    b.ToTable("school_context_scope_allowed_profile_sections", (string)null);
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.SchoolContextScopeAllowedRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MatrixId")
                        .HasColumnType("uuid")
                        .HasColumnName("matrix_id");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role_code");

                    b.Property<string>("TranslationKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("translation_key");

                    b.HasKey("Id");

                    b.HasIndex("MatrixId", "RoleCode")
                        .IsUnique();

                    b.ToTable("school_context_scope_allowed_roles", (string)null);
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.SchoolContextScopeAllowedUserManagementFlow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FlowCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("flow_code");

                    b.Property<Guid>("MatrixId")
                        .HasColumnType("uuid")
                        .HasColumnName("matrix_id");

                    b.Property<string>("TranslationKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("translation_key");

                    b.HasKey("Id");

                    b.HasIndex("MatrixId", "FlowCode")
                        .IsUnique();

                    b.ToTable("school_context_scope_allowed_user_management_flows", (string)null);
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.SchoolContextScopeCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CapabilityCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("capability_code");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("MatrixId")
                        .HasColumnType("uuid")
                        .HasColumnName("matrix_id");

                    b.Property<string>("TranslationKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("translation_key");

                    b.HasKey("Id");

                    b.HasIndex("MatrixId", "CapabilityCode")
                        .IsUnique();

                    b.ToTable("school_context_scope_capabilities", (string)null);
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.SchoolContextScopeMatrix", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("SchoolType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("school_type_code");

                    b.Property<string>("TranslationKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("translation_key");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SchoolType")
                        .IsUnique();

                    b.ToTable("school_context_scope_matrices", (string)null);
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.SchoolOperator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyNumberIco")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("company_number_ico");

                    b.Property<string>("DataBox")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("data_box");

                    b.Property<string>("DirectorSummary")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("director_summary");

                    b.Property<string>("LegalEntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_entity_name");

                    b.Property<string>("LegalForm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("legal_form");

                    b.Property<string>("OperatorEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("operator_email");

                    b.Property<string>("RedIzo")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("red_izo");

                    b.Property<string>("ResortIdentifier")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("resort_identifier");

                    b.Property<string>("StatutoryBodySummary")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("statutory_body_summary");

                    b.HasKey("Id");

                    b.HasIndex("CompanyNumberIco");

                    b.HasIndex("LegalEntityName");

                    b.HasIndex("RedIzo");

                    b.ToTable("school_operators", (string)null);
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.SchoolScopeOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MatrixId")
                        .HasColumnType("uuid")
                        .HasColumnName("matrix_id");

                    b.Property<bool?>("OverrideUsesAttendance")
                        .HasColumnType("boolean")
                        .HasColumnName("override_uses_attendance");

                    b.Property<bool?>("OverrideUsesClasses")
                        .HasColumnType("boolean")
                        .HasColumnName("override_uses_classes");

                    b.Property<bool?>("OverrideUsesDailyReports")
                        .HasColumnType("boolean")
                        .HasColumnName("override_uses_daily_reports");

                    b.Property<bool?>("OverrideUsesFieldOfStudy")
                        .HasColumnType("boolean")
                        .HasColumnName("override_uses_field_of_study");

                    b.Property<bool?>("OverrideUsesGrades")
                        .HasColumnType("boolean")
                        .HasColumnName("override_uses_grades");

                    b.Property<bool?>("OverrideUsesGroups")
                        .HasColumnType("boolean")
                        .HasColumnName("override_uses_groups");

                    b.Property<bool?>("OverrideUsesHomework")
                        .HasColumnType("boolean")
                        .HasColumnName("override_uses_homework");

                    b.Property<bool?>("OverrideUsesSubjects")
                        .HasColumnType("boolean")
                        .HasColumnName("override_uses_subjects");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.HasKey("Id");

                    b.HasIndex("MatrixId");

                    b.HasIndex("SchoolId")
                        .IsUnique();

                    b.ToTable("school_scope_overrides", (string)null);
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.SchoolYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("label");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("school_years", (string)null);
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.SecondaryFieldOfStudy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.HasKey("Id");

                    b.ToTable("secondary_fields_of_study", (string)null);
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.HasKey("Id");

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.TeacherAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClassRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_room_id");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("scope");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("TeacherUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_user_id");

                    b.Property<Guid?>("TeachingGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("teaching_group_id");

                    b.HasKey("Id");

                    b.ToTable("teacher_assignments", (string)null);
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.TeachingGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClassRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_room_id");

                    b.Property<bool>("IsDailyOperationsGroup")
                        .HasColumnType("boolean")
                        .HasColumnName("is_daily_operations_group");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.HasKey("Id");

                    b.ToTable("teaching_groups", (string)null);
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.Founder", b =>
                {
                    b.OwnsOne("Skolio.Organization.Domain.ValueObjects.Address", "FounderAddress", b1 =>
                        {
                            b1.Property<Guid>("FounderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("founder_address_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("founder_address_country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("founder_address_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("founder_address_street");

                            b1.HasKey("FounderId");

                            b1.ToTable("founders");

                            b1.WithOwner()
                                .HasForeignKey("FounderId");
                        });

                    b.Navigation("FounderAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.School", b =>
                {
                    b.HasOne("Skolio.Organization.Domain.Entities.Founder", "Founder")
                        .WithMany()
                        .HasForeignKey("FounderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Skolio.Organization.Domain.Entities.SchoolOperator", "SchoolOperator")
                        .WithMany()
                        .HasForeignKey("SchoolOperatorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Skolio.Organization.Domain.ValueObjects.Address", "MainAddress", b1 =>
                        {
                            b1.Property<Guid>("SchoolId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("main_address_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("main_address_country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("main_address_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("main_address_street");

                            b1.HasKey("SchoolId");

                            b1.ToTable("schools");

                            b1.WithOwner()
                                .HasForeignKey("SchoolId");
                        });

                    b.Navigation("Founder");

                    b.Navigation("MainAddress")
                        .IsRequired();

                    b.Navigation("SchoolOperator");
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.SchoolContextScopeAllowedAcademicsSection", b =>
                {
                    b.HasOne("Skolio.Organization.Domain.Entities.SchoolContextScopeMatrix", "Matrix")
                        .WithMany("AllowedAcademicsSections")
                        .HasForeignKey("MatrixId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Matrix");
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.SchoolContextScopeAllowedCreateUserFlow", b =>
                {
                    b.HasOne("Skolio.Organization.Domain.Entities.SchoolContextScopeMatrix", "Matrix")
                        .WithMany("AllowedCreateUserFlows")
                        .HasForeignKey("MatrixId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Matrix");
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.SchoolContextScopeAllowedOrganizationSection", b =>
                {
                    b.HasOne("Skolio.Organization.Domain.Entities.SchoolContextScopeMatrix", "Matrix")
                        .WithMany("AllowedOrganizationSections")
                        .HasForeignKey("MatrixId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Matrix");
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.SchoolContextScopeAllowedProfileSection", b =>
                {
                    b.HasOne("Skolio.Organization.Domain.Entities.SchoolContextScopeMatrix", "Matrix")
                        .WithMany("AllowedProfileSections")
                        .HasForeignKey("MatrixId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Matrix");
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.SchoolContextScopeAllowedRole", b =>
                {
                    b.HasOne("Skolio.Organization.Domain.Entities.SchoolContextScopeMatrix", "Matrix")
                        .WithMany("AllowedRoles")
                        .HasForeignKey("MatrixId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Matrix");
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.SchoolContextScopeAllowedUserManagementFlow", b =>
                {
                    b.HasOne("Skolio.Organization.Domain.Entities.SchoolContextScopeMatrix", "Matrix")
                        .WithMany("AllowedUserManagementFlows")
                        .HasForeignKey("MatrixId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Matrix");
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.SchoolContextScopeCapability", b =>
                {
                    b.HasOne("Skolio.Organization.Domain.Entities.SchoolContextScopeMatrix", "Matrix")
                        .WithMany("Capabilities")
                        .HasForeignKey("MatrixId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Matrix");
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.SchoolOperator", b =>
                {
                    b.OwnsOne("Skolio.Organization.Domain.ValueObjects.Address", "RegisteredOfficeAddress", b1 =>
                        {
                            b1.Property<Guid>("SchoolOperatorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("registered_office_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("registered_office_country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("registered_office_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("registered_office_street");

                            b1.HasKey("SchoolOperatorId");

                            b1.ToTable("school_operators");

                            b1.WithOwner()
                                .HasForeignKey("SchoolOperatorId");
                        });

                    b.Navigation("RegisteredOfficeAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.SchoolScopeOverride", b =>
                {
                    b.HasOne("Skolio.Organization.Domain.Entities.SchoolContextScopeMatrix", "Matrix")
                        .WithMany()
                        .HasForeignKey("MatrixId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skolio.Organization.Domain.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Matrix");

                    b.Navigation("School");
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.SchoolYear", b =>
                {
                    b.HasOne("Skolio.Organization.Domain.Entities.School", null)
                        .WithMany("SchoolYears")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Skolio.Organization.Domain.ValueObjects.SchoolYearPeriod", "Period", b1 =>
                        {
                            b1.Property<Guid>("SchoolYearId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("end_date");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("date")
                                .HasColumnName("start_date");

                            b1.HasKey("SchoolYearId");

                            b1.ToTable("school_years");

                            b1.WithOwner()
                                .HasForeignKey("SchoolYearId");
                        });

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.School", b =>
                {
                    b.Navigation("SchoolYears");
                });

            modelBuilder.Entity("Skolio.Organization.Domain.Entities.SchoolContextScopeMatrix", b =>
                {
                    b.Navigation("AllowedAcademicsSections");

                    b.Navigation("AllowedCreateUserFlows");

                    b.Navigation("AllowedOrganizationSections");

                    b.Navigation("AllowedProfileSections");

                    b.Navigation("AllowedRoles");

                    b.Navigation("AllowedUserManagementFlows");

                    b.Navigation("Capabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
